### ISSUE TITLE
Missing source code License

### ISSUE THREAD

**Issue by dotWee** [acederberg/pydantic-settings-yaml#16]
Please add a `LICENSE` file to your repository and make sure to define in your PyPi package!

**Comment by acederberg** [comment]
Hi @dotWee!

Thank you for using this package and making issues! I will do this (hopefully this evening) and post when it is done. Not gonna lie, I know very little about licensing and will have to research the matter first. 

Best,
Adrian

**Comment by acederberg** [comment]
@dotWee this is closed! Thank you for noticing!

License file is located under `LICENSE`. Location is specified for PyPI in `setup.cfg`. The license will appear in the next release.

**Comment by dotWee** [comment]
Thanks for the update! Make sure to place your name and current year in the placeholders 😉 

`Copyright (c) <year> <copyright holders>`

**Comment by acederberg** [comment]
@dotWee Yikes, my apologies! I did not even notice this. Will fix now. Sorry this took so long.
