### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_GenericAlias' and '_GenericAlias'

### ISSUE THREAD

**Issue by vm-bioinfo** [acederberg/pydantic-settings-yaml#17]

**Comment by vm-bioinfo** [comment]
please delete this issue

**Comment by acederberg** [comment]
@vm-bioinfo Hi! I saw you had issues with some sort of web app. Did it turn out to be elsewhere in your project?

NOTE: I will delete later, but I'd like to know nonetheless.
